# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField()),
                ('sensor_fr', models.FloatField()),
                ('sensor_fl', models.FloatField()),
                ('sensor_br', models.FloatField()),
                ('sensor_bl', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='poo',
            name='sensor_bl',
        ),
        migrations.RemoveField(
            model_name='poo',
            name='sensor_br',
        ),
        migrations.RemoveField(
            model_name='poo',
            name='sensor_fl',
        ),
        migrations.RemoveField(
            model_name='poo',
            name='sensor_fr',
        ),
        migrations.RemoveField(
            model_name='poo',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='measure',
            name='poo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poow.Poo'),
        ),
    ]
